### ISSUE TITLE
插件import的时候显示找不到模块  

### ISSUE THREAD

**Issue by jiansir** [lemontree2000/vue-magnify#2]
现代浏览器都没问题，但是这个问题在ie9 ie10上就有问题了_

![image](https://user-images.githubusercontent.com/29774269/56874110-2c128680-6a6a-11e9-9ebf-7878ad04a5cb.png)

**Comment by lemontree2000** [comment]
@jiansir  你这是用的ts吧， 请定义一个.d.ts 文件解决。 
```javascript

// src/lib.d.ts
declare module "vue-magnify" {
  const magnify:any
  export default magnify;
}
```

**Comment by jiansir** [comment]
嗯，谢谢   ts这块还不熟，我试试    我现在是把组件单独拿出来用了
